[theme]
primaryColor = "#125C64"
backgroundColor = "#F4F6F5"
secondaryBackgroundColor = "#EAF1EF"
textColor = "#203438"
font = "sans serif"

[server]
headless = true
maxUploadSize = 5

[browser]
gatherUsageStats = false
